# Site settings
title: Charles and Gaby
email: wedding@houseabsolute.co.uk
url: https://wedding.houseabsolute.co.uk
baseurl: ""
description: "We're getting married and can't wait to celebrate with you!"
host: 0.0.0.0 # listen to LAN connections
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - vendor/

# Background image
default_background_image: img/header.jpg
# faq:
#   - question: What should I wear?
#     answer: |
#       The dress code for our wedding is formal attire. For women, cocktail dresses or formal gowns are appropriate. For men, suits or tuxedos are recommended.
#   - question: Will transportation be provided?
#     answer: |
#       Yes! We will have shuttle service running between the ceremony venue, reception venue, and recommended hotels throughout the evening.
#   - question: Is there parking available?
#     answer: |
#       Complimentary parking is available at both the ceremony and reception venues. Detailed parking instructions will be provided closer to the date.
#   - question: Can I bring a date?
#     answer: |
#       Please refer to your invitation for the number of guests invited. If your invitation includes "and guest," you are welcome to bring a plus one.
#   - question: Will there be vegetarian/vegan options?
#     answer: |
#       Yes! Our menu will include vegetarian options. Please indicate any dietary restrictions on your RSVP card, and we'll do our best to accommodate.
#   - question: What time should I arrive?
#     answer: |
#       We recommend arriving 20-30 minutes before the ceremony start time to allow for parking and seating.
#   - question: Are children welcome?
#     answer: |
#       We love your little ones, but we've decided to make our wedding an adults-only celebration. We hope this gives you a chance to relax and enjoy the evening!

# Navigation links for the main nav bar
navigation:
  - title: "C & G"
    url: "/"
  - title: "Location"
    url: "/location/"
  - title: "Ceremony"
    url: "/ceremony/"
  - title: "Activities"
    url: "/activities/"
  - title: RSVP
    url: "/rsvp/"
# calendar:
#   ical: https://www.google.com/calendar/ical/YOUR_CALENDAR_ID/public/basic.ics
#   google_id: YOUR_CALENDAR_ID@group.calendar.google.com
